name: "WP-CVE-Scanner"

services:
### START: WP-SCAN SERVICES ###
  wp-cve-scan:
    build:
      context: ./wp-cve-scan
      dockerfile: Dockerfile
    container_name: wp-cve-scan
    # This application requires access to the Docker socket to run
    # the WP-CLI container to scan WordPress sites.
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    # - ./wp-cve-scan/ssh-keys:/usr/src/app/wp-cve-scan/ssh-keys
    - ./wp-cve-scan/files:/usr/src/app/wp-cve-scan/files
    # networks:
    #   - wp-cve-scan-network
    ports:
      - "5040:5040"
    # depends_on:
    #    - wp-cli
    #    - nist-cve-search

  # nist-cve-search:
  #   build:
  #     context: ./nist-cve-search
  #     dockerfile: Dockerfile
  #   container_name: nist-cve-search
  #   networks:
  #     - wp-cve-scan-network
  #   ports:
  #     - "4000:4000"

  # wp-cli:
  #   image: wordpress:cli
  #   networks:
  #     - wp-cve-scan-network
  #   entrypoint: ["wp"]
  #   command: ["--info"]
### END: WP-SCAN SERVICES ###

networks:
  wp-cve-scan-network:
    driver: bridge