name: "WP-CVE-Scanner"

services:
### START: WP-SCAN SERVICES ###
  wp-cve-scan:
    build:
      context: ./wp-cve-scan
      dockerfile: Dockerfile
    container_name: wp-cve-scan
    # This application requires access to the Docker socket to run
    # the WP-CLI container to scan WordPress sites.
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    # - ./wp-cve-scan/ssh-keys:/usr/src/app/wp-cve-scan/ssh-keys
    - ./wp-cve-scan/files:/usr/src/app/wp-cve-scan/files
    ports:
      - "5040:5040"